// Code generated by [/tmp/go-build808418507/b001/exe/generator -lexstring mlToken -pkg tk9_0 <...>], DO NOT EDIT.

package tk9_0

// mlToken recognizes longest ASCII lexemes. Lower IDs take precedence on same length.
//
//	id   0: <...>
//	id   1: \$([^$]|\\\$)*\$
//	id   2: \$\$?([^$]|\\\$)*\$\$?
//
// ID == -1 is returned when no lexeme was recognized.
func mlToken(s string) (id, length int) {
	const endOfText = 0x110000
	var pos, pos0, width, width1 int
	id = -1
	var r, r1 rune
	_ = pos0
	_ = r
	_ = r1
	_ = width1
	step := func(pos int) (rune, int) {
		if pos < len(s) {
			return rune(s[pos]), 1
		}
		return endOfText, 0
	}
	move := func() {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
	}
	accept := func(x rune) bool {
		if r == x {
			move()
			return true
		}
		return false
	}
	_ = accept
	accept2 := func(x rune) bool {
		if r <= x {
			move()
			return true
		}
		return false
	}
	_ = accept2
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	id, length = 0, pos
	if accept('$') {
		goto l8
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l5out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l5out:
	return id, length
l8:
	if accept('$') {
		goto l15
	}
	if accept('\\') {
		goto l51
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l12out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l12out:
	return id, length
l15:
	id, length = 1, pos
	if accept('$') {
		goto l23
	}
	if accept('\\') {
		goto l29
	}
	if accept2('#') {
		goto l44
	}
	if r < '%' {
		goto l20out
	}
	if accept2('\U0010ffff') {
		goto l44
	}
l20out:
	return id, length
l23:
	id, length = 2, pos
	if accept('$') {
		goto l27
	}
	return id, length
l27:
	id, length = 2, pos
	return id, length
l29:
	if accept('$') {
		goto l36
	}
	if accept('\\') {
		goto l29
	}
	if accept2('#') {
		goto l44
	}
	if r < '%' {
		goto l33out
	}
	if accept2('\U0010ffff') {
		goto l44
	}
l33out:
	return id, length
l36:
	id, length = 2, pos
	if accept('$') {
		goto l23
	}
	if accept('\\') {
		goto l29
	}
	if accept2('#') {
		goto l44
	}
	if r < '%' {
		goto l41out
	}
	if accept2('\U0010ffff') {
		goto l44
	}
l41out:
	return id, length
l44:
	if accept('$') {
		goto l23
	}
	if accept('\\') {
		goto l29
	}
	if accept2('#') {
		goto l44
	}
	if r < '%' {
		goto l48out
	}
	if accept2('\U0010ffff') {
		goto l44
	}
l48out:
	return id, length
l51:
	if accept('$') {
		goto l58
	}
	if accept('\\') {
		goto l51
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l55out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l55out:
	return id, length
l58:
	id, length = 1, pos
	if accept('$') {
		goto l66
	}
	if accept('\\') {
		goto l51
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l63out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l63out:
	return id, length
l66:
	id, length = 1, pos
	if accept('$') {
		goto l27
	}
	return id, length
l70:
	if accept('$') {
		goto l66
	}
	if accept('\\') {
		goto l51
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l74out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l74out:
	return id, length
l77:
	id, length = 0, pos
	if accept('$') {
		goto l85
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l82out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l82out:
	return id, length
l85:
	id, length = 0, pos
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l88out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l88out:
	return id, length
l91:
	id, length = 0, pos
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l94out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l94out:
	return id, length

	id, length = 0, pos
	if accept('$') {
		goto l8
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l102out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l102out:
	return id, length
}
