// Code generated by [/tmp/go-build1417745848/b001/exe/generator -lexstring mlToken -pkg tk9_0 <...>], DO NOT EDIT.

package tk9_0

// mlToken recognizes longest ASCII lexemes. Lower IDs take precedence on same length.
//
//	id   0: <...>
//	id   1: \$([^$]|\\\$)*\$
//	id   2: \$\$([^$]|\\\$)*\$\$
//
// ID == -1 is returned when no lexeme was recognized.
func mlToken(s string) (id, length int) {
	const endOfText = 0x110000
	var pos, pos0, width, width1 int
	id = -1
	var r, r1 rune
	_ = pos0
	_ = r
	_ = r1
	_ = width1
	step := func(pos int) (rune, int) {
		if pos < len(s) {
			return rune(s[pos]), 1
		}
		return endOfText, 0
	}
	move := func() {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
	}
	accept := func(x rune) bool {
		if r == x {
			move()
			return true
		}
		return false
	}
	_ = accept
	accept2 := func(x rune) bool {
		if r <= x {
			move()
			return true
		}
		return false
	}
	_ = accept2
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	id, length = 0, pos
	if accept('$') {
		goto l8
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l5out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l5out:
	return id, length
l8:
	if accept('$') {
		goto l15
	}
	if accept('\\') {
		goto l53
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l12out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l12out:
	return id, length
l15:
	id, length = 1, pos
	if accept('$') {
		goto l23
	}
	if accept('\\') {
		goto l28
	}
	if accept2('#') {
		goto l46
	}
	if r < '%' {
		goto l20out
	}
	if accept2('\U0010ffff') {
		goto l46
	}
l20out:
	return id, length
l23:
	if accept('$') {
		goto l26
	}
	return id, length
l26:
	id, length = 2, pos
	return id, length
l28:
	if accept('$') {
		goto l35
	}
	if accept('\\') {
		goto l28
	}
	if accept2('#') {
		goto l46
	}
	if r < '%' {
		goto l32out
	}
	if accept2('\U0010ffff') {
		goto l46
	}
l32out:
	return id, length
l35:
	if accept('$') {
		goto l42
	}
	if accept('\\') {
		goto l28
	}
	if accept2('#') {
		goto l46
	}
	if r < '%' {
		goto l39out
	}
	if accept2('\U0010ffff') {
		goto l46
	}
l39out:
	return id, length
l42:
	id, length = 2, pos
	if accept('$') {
		goto l26
	}
	return id, length
l46:
	if accept('$') {
		goto l23
	}
	if accept('\\') {
		goto l28
	}
	if accept2('#') {
		goto l46
	}
	if r < '%' {
		goto l50out
	}
	if accept2('\U0010ffff') {
		goto l46
	}
l50out:
	return id, length
l53:
	if accept('$') {
		goto l60
	}
	if accept('\\') {
		goto l53
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l57out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l57out:
	return id, length
l60:
	id, length = 1, pos
	if accept('$') {
		goto l68
	}
	if accept('\\') {
		goto l53
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l65out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l65out:
	return id, length
l68:
	id, length = 1, pos
	return id, length
l70:
	if accept('$') {
		goto l68
	}
	if accept('\\') {
		goto l53
	}
	if accept2('#') {
		goto l70
	}
	if r < '%' {
		goto l74out
	}
	if accept2('\U0010ffff') {
		goto l70
	}
l74out:
	return id, length
l77:
	id, length = 0, pos
	if accept('$') {
		goto l85
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l82out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l82out:
	return id, length
l85:
	id, length = 0, pos
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l88out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l88out:
	return id, length
l91:
	id, length = 0, pos
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l94out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l94out:
	return id, length

	id, length = 0, pos
	if accept('$') {
		goto l8
	}
	if accept('\\') {
		goto l77
	}
	if accept2('#') {
		goto l91
	}
	if r < '%' {
		goto l102out
	}
	if accept2('\U0010ffff') {
		goto l91
	}
l102out:
	return id, length
}
